services:
  - type: web
    name: mbl-igaming-backend
    runtime: node
    plan: free
    buildCommand: |
      cd backend
      npm install
      npx prisma generate
      npm run build
    startCommand: |
      cd backend
      npx prisma migrate deploy
      npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: SESSION_DURATION_SECONDS
        value: 60
      - key: SESSION_MAX_PLAYERS
        value: 10
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: DATABASE_URL
        value: "YOUR_DATABASE_URL_HERE"
      - key: JWT_SECRET
        generateValue: true 