export const SESSION_CONSTANTS = {
  DEFAULT_DURATION_SECONDS: 20,
  DEFAULT_MAX_PLAYERS: 10,
  MIN_PICK_NUMBER: 1,
  MAX_PICK_NUMBER: 9,
  SESSION_STATUSES: {
    PENDING: 'PENDING',
    ACTIVE: 'ACTIVE',
    ENDED: 'ENDED',
  },
} as const; 